### ISSUE TITLE
beeswarm: mobile

### ISSUE THREAD

**Issue by jadiehm** [the-pudding/vogue#10]

**Comment by jadiehm** [comment]
- radius based on width
- no face swap
- face text span

**Comment by jadiehm** [comment]
- remove face toggle

**Comment by jadiehm** [comment]
- [x] radius based on width
- [x] no face swap
- [x] face text span
- [x] remove face toggle

**Comment by ProQuestionAsker** [comment]
- [x] Check y axis on mobile (gets cut off)
